/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./routes/__root"
import { Route as LoginRouteImport } from "./routes/login"
import { Route as appregisterAuthGuardRouteImport } from "./routes/(app)/(register)/_authGuard"
import { Route as appdemoAuthGuardRouteImport } from "./routes/(app)/(demo)/_authGuard"
import { Route as appregisterAuthGuardIndexRouteImport } from "./routes/(app)/(register)/_authGuard/index"
import { Route as appdemoAuthGuardDemoRouteRouteImport } from "./routes/(app)/(demo)/_authGuard/demo.route"
import { Route as appdemoAuthGuardDemoIndexRouteImport } from "./routes/(app)/(demo)/_authGuard/demo.index"

const LoginRoute = LoginRouteImport.update({
  id: "/login",
  path: "/login",
  getParentRoute: () => rootRouteImport,
} as any)
const appregisterAuthGuardRoute = appregisterAuthGuardRouteImport.update({
  id: "/(app)/(register)/_authGuard",
  getParentRoute: () => rootRouteImport,
} as any)
const appdemoAuthGuardRoute = appdemoAuthGuardRouteImport.update({
  id: "/(app)/(demo)/_authGuard",
  getParentRoute: () => rootRouteImport,
} as any)
const appregisterAuthGuardIndexRoute =
  appregisterAuthGuardIndexRouteImport.update({
    id: "/",
    path: "/",
    getParentRoute: () => appregisterAuthGuardRoute,
  } as any)
const appdemoAuthGuardDemoRouteRoute =
  appdemoAuthGuardDemoRouteRouteImport.update({
    id: "/demo",
    path: "/demo",
    getParentRoute: () => appdemoAuthGuardRoute,
  } as any)
const appdemoAuthGuardDemoIndexRoute =
  appdemoAuthGuardDemoIndexRouteImport.update({
    id: "/",
    path: "/",
    getParentRoute: () => appdemoAuthGuardDemoRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  "/login": typeof LoginRoute
  "/demo": typeof appdemoAuthGuardDemoRouteRouteWithChildren
  "/": typeof appregisterAuthGuardIndexRoute
  "/demo/": typeof appdemoAuthGuardDemoIndexRoute
}
export interface FileRoutesByTo {
  "/login": typeof LoginRoute
  "/": typeof appregisterAuthGuardIndexRoute
  "/demo": typeof appdemoAuthGuardDemoIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  "/login": typeof LoginRoute
  "/(app)/(demo)/_authGuard": typeof appdemoAuthGuardRouteWithChildren
  "/(app)/(register)/_authGuard": typeof appregisterAuthGuardRouteWithChildren
  "/(app)/(demo)/_authGuard/demo": typeof appdemoAuthGuardDemoRouteRouteWithChildren
  "/(app)/(register)/_authGuard/": typeof appregisterAuthGuardIndexRoute
  "/(app)/(demo)/_authGuard/demo/": typeof appdemoAuthGuardDemoIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: "/login" | "/demo" | "/" | "/demo/"
  fileRoutesByTo: FileRoutesByTo
  to: "/login" | "/" | "/demo"
  id:
    | "__root__"
    | "/login"
    | "/(app)/(demo)/_authGuard"
    | "/(app)/(register)/_authGuard"
    | "/(app)/(demo)/_authGuard/demo"
    | "/(app)/(register)/_authGuard/"
    | "/(app)/(demo)/_authGuard/demo/"
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  LoginRoute: typeof LoginRoute
  appdemoAuthGuardRoute: typeof appdemoAuthGuardRouteWithChildren
  appregisterAuthGuardRoute: typeof appregisterAuthGuardRouteWithChildren
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/login": {
      id: "/login"
      path: "/login"
      fullPath: "/login"
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/(app)/(register)/_authGuard": {
      id: "/(app)/(register)/_authGuard"
      path: ""
      fullPath: ""
      preLoaderRoute: typeof appregisterAuthGuardRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/(app)/(demo)/_authGuard": {
      id: "/(app)/(demo)/_authGuard"
      path: ""
      fullPath: ""
      preLoaderRoute: typeof appdemoAuthGuardRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/(app)/(register)/_authGuard/": {
      id: "/(app)/(register)/_authGuard/"
      path: "/"
      fullPath: "/"
      preLoaderRoute: typeof appregisterAuthGuardIndexRouteImport
      parentRoute: typeof appregisterAuthGuardRoute
    }
    "/(app)/(demo)/_authGuard/demo": {
      id: "/(app)/(demo)/_authGuard/demo"
      path: "/demo"
      fullPath: "/demo"
      preLoaderRoute: typeof appdemoAuthGuardDemoRouteRouteImport
      parentRoute: typeof appdemoAuthGuardRoute
    }
    "/(app)/(demo)/_authGuard/demo/": {
      id: "/(app)/(demo)/_authGuard/demo/"
      path: "/"
      fullPath: "/demo/"
      preLoaderRoute: typeof appdemoAuthGuardDemoIndexRouteImport
      parentRoute: typeof appdemoAuthGuardDemoRouteRoute
    }
  }
}

interface appdemoAuthGuardDemoRouteRouteChildren {
  appdemoAuthGuardDemoIndexRoute: typeof appdemoAuthGuardDemoIndexRoute
}

const appdemoAuthGuardDemoRouteRouteChildren: appdemoAuthGuardDemoRouteRouteChildren =
  {
    appdemoAuthGuardDemoIndexRoute: appdemoAuthGuardDemoIndexRoute,
  }

const appdemoAuthGuardDemoRouteRouteWithChildren =
  appdemoAuthGuardDemoRouteRoute._addFileChildren(
    appdemoAuthGuardDemoRouteRouteChildren,
  )

interface appdemoAuthGuardRouteChildren {
  appdemoAuthGuardDemoRouteRoute: typeof appdemoAuthGuardDemoRouteRouteWithChildren
}

const appdemoAuthGuardRouteChildren: appdemoAuthGuardRouteChildren = {
  appdemoAuthGuardDemoRouteRoute: appdemoAuthGuardDemoRouteRouteWithChildren,
}

const appdemoAuthGuardRouteWithChildren =
  appdemoAuthGuardRoute._addFileChildren(appdemoAuthGuardRouteChildren)

interface appregisterAuthGuardRouteChildren {
  appregisterAuthGuardIndexRoute: typeof appregisterAuthGuardIndexRoute
}

const appregisterAuthGuardRouteChildren: appregisterAuthGuardRouteChildren = {
  appregisterAuthGuardIndexRoute: appregisterAuthGuardIndexRoute,
}

const appregisterAuthGuardRouteWithChildren =
  appregisterAuthGuardRoute._addFileChildren(appregisterAuthGuardRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  LoginRoute: LoginRoute,
  appdemoAuthGuardRoute: appdemoAuthGuardRouteWithChildren,
  appregisterAuthGuardRoute: appregisterAuthGuardRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
